source "https://rubygems.org"
ruby '2.7.3'
source 'https://rubygems.org'

group :development, :test do
  gem 'bosh-template', '2.3.0'
  gem 'rspec', '3.11.0'
  gem 'rspec-its', '1.3.0'
end

gem "yaml", "~> 0.2.0"
